# Changes here will be overwritten by Copier
_commit: 0.1.0
_src_path: gh:mkdocstrings/handler-template
author_email: pawamoy@pm.me
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2022'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: pawamoy@pm.me
copyright_license: ISC License
language: javascript
project_description: Javascript handler for mkdocstrings.
project_name: mkdocstrings-javascript
python_package_distribution_name: mkdocstrings-javascript
python_package_import_name: javascript
repository_name: javascript
repository_namespace: mkdocstrings
repository_provider: github.com

