site_name: "mkdocstrings-javascript"
site_description: "Javascript handler for mkdocstrings."
site_url: "https://mkdocstrings.github.io/javascript"
repo_url: "https://github.com/mkdocstrings/javascript"
repo_name: "mkdocstrings/javascript"
site_dir: "site"

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
# defer to gen-files + literate-nav
- Code Reference: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md
  - mkdocstrings: https://mkdocstrings.github.io/

theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
  - navigation.tabs
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_credits.py
    - docs/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.md
- coverage
- section-index
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://mkdocstrings.github.io/objects.inv
        selection:
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
        rendering:
          show_submodules: no
          merge_init_into_class: yes
    watch:
    - src/mkdocstrings_handlers

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/pawamoy
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/pawamoy
